<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>modernwms-ruiyi-7b722e6a-0b50-4ed5-9f19-8e289e3dd9f7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="6.1.4" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModernWMS.Core\ModernWMS.Core.csproj" />
    <ProjectReference Include="..\ModernWMS.WMS\ModernWMS.WMS.csproj" />
  </ItemGroup>

</Project>
