// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModernWMS.Core.DBContext;

#nullable disable

namespace ModernWMS.Migrations
{
    [DbContext(typeof(SqlDBContext))]
    partial class SqlDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ModernWMS.Core.DBContext.Entities.ErpReceiptRecordEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("actual_receipt_qty")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long>("inbound_qty")
                        .HasColumnType("bigint");

                    b.Property<string>("loss_files_json")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("loss_qty")
                        .HasColumnType("bigint");

                    b.Property<string>("loss_reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("receipt_files_json")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("receipt_freight_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("receipt_freight_files_json")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("receipt_freight_payment_status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("receipt_remark")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long>("shipment_id")
                        .HasColumnType("bigint");

                    b.Property<int>("source_version")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("shipment_id")
                        .IsUnique();

                    b.ToTable("wms_erp_receipt");
                });

            modelBuilder.Entity("ModernWMS.Core.Models.GlobalUniqueSerialEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("current_no")
                        .HasColumnType("int");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("prefix_char")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("reset_rule")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("table_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("wms_global_unique_serial");
                });

            modelBuilder.Entity("ModernWMS.Core.Models.UserroleEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("is_valid")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("wms_userrole");
                });

            modelBuilder.Entity("ModernWMS.Core.Models.userEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("auth_string")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("contact_tel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("is_valid")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("sex")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("user_num")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("user_role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("wms_user");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.ActionLogEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("action_content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("action_time")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("vue_path")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("wms_action_log");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.Approve.FlowSetMainEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("flow_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("menu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("wms_flowsetmain");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.AsnEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("actual_qty")
                        .HasColumnType("int");

                    b.Property<DateTime>("arrival_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("asn_no")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("asn_qty")
                        .HasColumnType("int");

                    b.Property<byte>("asn_status")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("asnmaster_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("damage_qty")
                        .HasColumnType("int");

                    b.Property<DateTime>("expiry_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("int");

                    b.Property<string>("goods_owner_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("is_valid")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("more_qty")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("shortage_qty")
                        .HasColumnType("int");

                    b.Property<int>("sku_id")
                        .HasColumnType("int");

                    b.Property<int>("sorted_qty")
                        .HasColumnType("int");

                    b.Property<int>("spu_id")
                        .HasColumnType("int");

                    b.Property<int>("supplier_id")
                        .HasColumnType("int");

                    b.Property<string>("supplier_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<string>("unload_person")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("unload_person_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("unload_time")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("volume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("asnmaster_id");

                    b.ToTable("wms_asn");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.AsnmasterEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("asn_batch")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("asn_no")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("asn_status")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("estimated_arrival_time")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("int");

                    b.Property<string>("goods_owner_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("volume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.ToTable("wms_asnmaster");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.AsnsortEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("asn_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("is_valid")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("putaway_qty")
                        .HasColumnType("int");

                    b.Property<string>("series_number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("sorted_qty")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("wms_asnsort");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.CompanyEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("company_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("contact_tel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("manager")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("wms_company");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.DispatchWeighingBoxEntity", b =>
                {
                    b.Property<int>("id").ValueGeneratedOnAdd().HasColumnType("int");
                    b.Property<int>("box_index").HasColumnType("int");
                    b.Property<string>("box_no").IsRequired().HasMaxLength(64).HasColumnType("varchar(64)");
                    b.Property<long?>("copied_from_erp_box_id").HasColumnType("bigint");
                    b.Property<DateTime>("create_time").HasColumnType("datetime(6)");
                    b.Property<string>("dispatch_no").IsRequired().HasMaxLength(32).HasColumnType("varchar(32)");
                    b.Property<long>("erp_box_id").HasColumnType("bigint");
                    b.Property<string>("fba_no").IsRequired().HasMaxLength(64).HasColumnType("varchar(64)");
                    b.Property<long>("fba_shipment_id").HasColumnType("bigint");
                    b.Property<DateTime>("last_update_time").IsConcurrencyToken().HasColumnType("datetime(6)");
                    b.Property<long>("tenant_id").HasColumnType("bigint");
                    b.Property<string>("tracking_id").IsRequired().HasMaxLength(128).HasColumnType("varchar(128)");
                    b.Property<decimal>("weighing_height").HasColumnType("decimal(18,2)");
                    b.Property<decimal>("weighing_length").HasColumnType("decimal(18,2)");
                    b.Property<string>("weighing_person").IsRequired().HasMaxLength(64).HasColumnType("varchar(64)");
                    b.Property<int>("weighing_person_id").HasColumnType("int");
                    b.Property<DateTime>("weighing_time").HasColumnType("datetime(6)");
                    b.Property<decimal>("weighing_volume").HasColumnType("decimal(18,2)");
                    b.Property<decimal>("weighing_weight").HasColumnType("decimal(18,2)");
                    b.Property<decimal>("weighing_width").HasColumnType("decimal(18,2)");
                    b.HasKey("id");
                    b.HasIndex("tenant_id", "dispatch_no");
                    b.HasIndex("tenant_id", "erp_box_id").IsUnique();
                    b.HasIndex("tenant_id", "fba_shipment_id");
                    b.ToTable("wms_dispatch_weighing_box");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.DispatchlistEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("actual_qty")
                        .HasColumnType("int");

                    b.Property<string>("carrier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("damage_qty")
                        .HasColumnType("int");

                    b.Property<string>("dispatch_no")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("dispatch_status")
                        .HasColumnType("tinyint unsigned");

                    b.Property<decimal>("freightfee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("intrasit_qty")
                        .HasColumnType("int");

                    b.Property<DateTime>("last_update_time")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("lock_qty")
                        .HasColumnType("int");

                    b.Property<string>("package_no")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("package_person")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("package_qty")
                        .HasColumnType("int");

                    b.Property<DateTime>("package_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("pick_checker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("pick_checker_id")
                        .HasColumnType("int");

                    b.Property<int>("picked_qty")
                        .HasColumnType("int");

                    b.Property<int>("qty")
                        .HasColumnType("int");

                    b.Property<int>("sign_qty")
                        .HasColumnType("int");

                    b.Property<int>("sku_id")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("volume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("waybill_no")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("weighing_no")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("weighing_person")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("weighing_qty")
                        .HasColumnType("int");

                    b.Property<decimal>("weighing_weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("weighing_height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("weighing_length")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("weighing_volume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("weighing_width")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.ToTable("wms_dispatchlist");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.DispatchpicklistEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("dispatchlist_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("expiry_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("goods_location_id")
                        .HasColumnType("int");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_update_stock")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("pick_qty")
                        .HasColumnType("int");

                    b.Property<int>("picked_qty")
                        .HasColumnType("int");

                    b.Property<string>("picker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("picker_id")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("putaway_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("series_number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("sku_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("dispatchlist_id");

                    b.ToTable("wms_dispatchpicklist");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.FlowSetEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("flowsetmain_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_end")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("is_origin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("node_guid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("node_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("prev_node_guid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("flowsetmain_id");

                    b.ToTable("wms_flowset");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.FlowSetFilterEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("assert_mode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("c1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("c2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("col_label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("col_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("compare")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("condition_group")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("flowset_id")
                        .HasColumnType("int");

                    b.Property<int>("flowsetmain_id")
                        .HasColumnType("int");

                    b.Property<string>("formulas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("logic")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("node_guid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("scheme_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("sort")
                        .HasColumnType("int");

                    b.Property<string>("table_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("flowset_id");

                    b.ToTable("wms_flowsetfilter");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.FlowSetUserEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("flowset_id")
                        .HasColumnType("int");

                    b.Property<int>("flowsetmain_id")
                        .HasColumnType("int");

                    b.Property<string>("node_guid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("flowset_id");

                    b.ToTable("wms_flowsetusers");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.FreightfeeEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("arrival_city")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("carrier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("departure_city")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("is_valid")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("min_payment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("price_per_volume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("price_per_weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("wms_freightfee");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.GoodslocationEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("is_valid")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("layer_number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("location_heigth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("location_length")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("location_load")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("location_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("location_volume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("location_width")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("roadway_number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("shelf_number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("tag_number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<int>("warehouse_area_id")
                        .HasColumnType("int");

                    b.Property<string>("warehouse_area_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("warehouse_area_property")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("warehouse_id")
                        .HasColumnType("int");

                    b.Property<string>("warehouse_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("wms_goodslocation");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.GoodsownerEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("contact_tel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("goods_owner_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("is_valid")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("manager")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("wms_goodsowner");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.MenuEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("menu_actions")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("menu_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("module")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("sort")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<string>("vue_directory")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("vue_path")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("vue_path_detail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("wms_menu");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.PrintSolutionEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("config_json")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("report_direction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("report_length")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("report_width")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("solution_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("tab_page")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<string>("vue_path")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("wms_user_defined_print_solution");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.RolemenuEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte>("authority")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("menu_actions_authority")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("menu_id")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<int>("userrole_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("wms_rolemenu");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.SkuEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("bar_code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("lenght")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("sku_code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("sku_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("spu_id")
                        .HasColumnType("int");

                    b.Property<string>("unit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("volume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("width")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("spu_id");

                    b.ToTable("wms_sku");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.SkuSafetyStockEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("safety_stock_qty")
                        .HasColumnType("int");

                    b.Property<int>("sku_id")
                        .HasColumnType("int");

                    b.Property<int>("warehouse_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("sku_id");

                    b.ToTable("wms_sku_safety_stock");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.SpuEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("is_valid")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("length_unit")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("origin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("spu_code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("spu_description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("spu_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("supplier_id")
                        .HasColumnType("int");

                    b.Property<string>("supplier_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<byte>("volume_unit")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("weight_unit")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("id");

                    b.ToTable("wms_spu");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.StockEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("expiry_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("goods_location_id")
                        .HasColumnType("int");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_freeze")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("last_update_time")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("putaway_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("qty")
                        .HasColumnType("int");

                    b.Property<string>("series_number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("sku_id")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("wms_stock");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.StockadjustEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("expiry_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("goods_location_id")
                        .HasColumnType("int");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_update_stock")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("job_code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("job_type")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("putaway_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("qty")
                        .HasColumnType("int");

                    b.Property<string>("series_number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("sku_id")
                        .HasColumnType("int");

                    b.Property<int>("source_table_id")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("wms_stockadjust");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.StockfreezeEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("goods_location_id")
                        .HasColumnType("int");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("handle_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("handler")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("job_code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("job_type")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("series_number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("sku_id")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("wms_stockfreeze");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.StockmoveEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("dest_googs_location_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("expiry_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("handle_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("handler")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("job_code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("move_status")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("orig_goods_location_id")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("putaway_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("qty")
                        .HasColumnType("int");

                    b.Property<string>("series_number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("sku_id")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("wms_stockmove");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.StockprocessEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("job_code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("job_type")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("process_status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("process_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("processor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("wms_stockprocess");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.StockprocessdetailEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("expiry_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("goods_location_id")
                        .HasColumnType("int");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_source")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("is_update_stock")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("putaway_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("qty")
                        .HasColumnType("int");

                    b.Property<string>("series_number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("sku_id")
                        .HasColumnType("int");

                    b.Property<int>("stock_process_id")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("stock_process_id");

                    b.ToTable("wms_stockprocessdetail");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.StocktakingEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("book_qty")
                        .HasColumnType("int");

                    b.Property<int>("counted_qty")
                        .HasColumnType("int");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("difference_qty")
                        .HasColumnType("int");

                    b.Property<DateTime>("expiry_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("goods_location_id")
                        .HasColumnType("int");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("handle_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("handler")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("job_code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("job_status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("putaway_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("series_number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("sku_id")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("wms_stocktaking");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.SupplierEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("contact_tel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("is_valid")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("manager")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("supplier_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("wms_supplier");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.WarehouseEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("contact_tel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("erp_warehouse_id")
                        .HasColumnType("bigint");

                    b.Property<bool>("is_valid")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("manager")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<string>("warehouse_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("erp_warehouse_id")
                        .IsUnique();

                    b.ToTable("wms_warehouse");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.WarehouseareaEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("area_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("area_property")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("is_valid")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("parent_id")
                        .HasColumnType("int");

                    b.Property<int>("sort")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<int>("warehouse_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("wms_warehousearea");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.AsnEntity", b =>
                {
                    b.HasOne("ModernWMS.WMS.Entities.Models.AsnmasterEntity", "Asnmaster")
                        .WithMany("detailList")
                        .HasForeignKey("asnmaster_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asnmaster");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.DispatchpicklistEntity", b =>
                {
                    b.HasOne("ModernWMS.WMS.Entities.Models.DispatchlistEntity", "Dispatchlist")
                        .WithMany("detailList")
                        .HasForeignKey("dispatchlist_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dispatchlist");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.FlowSetEntity", b =>
                {
                    b.HasOne("ModernWMS.WMS.Entities.Models.Approve.FlowSetMainEntity", "FlowMainSet")
                        .WithMany("flowset_list")
                        .HasForeignKey("flowsetmain_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlowMainSet");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.FlowSetFilterEntity", b =>
                {
                    b.HasOne("ModernWMS.WMS.Entities.Models.FlowSetEntity", "FlowSet")
                        .WithMany("filter_list")
                        .HasForeignKey("flowset_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlowSet");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.FlowSetUserEntity", b =>
                {
                    b.HasOne("ModernWMS.WMS.Entities.Models.FlowSetEntity", "FlowSet")
                        .WithMany("user_list")
                        .HasForeignKey("flowset_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlowSet");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.SkuEntity", b =>
                {
                    b.HasOne("ModernWMS.WMS.Entities.Models.SpuEntity", "Spu")
                        .WithMany("detailList")
                        .HasForeignKey("spu_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spu");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.SkuSafetyStockEntity", b =>
                {
                    b.HasOne("ModernWMS.WMS.Entities.Models.SkuEntity", "Sku")
                        .WithMany("detailList")
                        .HasForeignKey("sku_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sku");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.StockprocessdetailEntity", b =>
                {
                    b.HasOne("ModernWMS.WMS.Entities.Models.StockprocessEntity", "Stockprocess")
                        .WithMany("detailList")
                        .HasForeignKey("stock_process_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stockprocess");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.Approve.FlowSetMainEntity", b =>
                {
                    b.Navigation("flowset_list");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.AsnmasterEntity", b =>
                {
                    b.Navigation("detailList");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.DispatchlistEntity", b =>
                {
                    b.Navigation("detailList");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.FlowSetEntity", b =>
                {
                    b.Navigation("filter_list");

                    b.Navigation("user_list");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.SkuEntity", b =>
                {
                    b.Navigation("detailList");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.SpuEntity", b =>
                {
                    b.Navigation("detailList");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.StockprocessEntity", b =>
                {
                    b.Navigation("detailList");
                });
#pragma warning restore 612, 618
        }
    }
}
