<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModernWMS.Core\ModernWMS.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AlibabaCloud.OSS.V2" Version="0.2.0" />
  </ItemGroup>

</Project>
